In [67]:
import pandas as pd
import random

In [58]:
df = pd.read_excel("sample.xlsx", sheet_name="Data", header=6)

In [59]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16495 entries, 0 to 16494
Data columns (total 27 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Unnamed: 0              0 non-null      float64
 1   Original Vendor         16495 non-null  object
 2   Deduped Vendor          16495 non-null  object
 3   Invoice Description     16495 non-null  object
 4   GL Description          16495 non-null  object
 5   Amount                  16495 non-null  float64
 6   Date                    16495 non-null  datetime64[ns]
 7   Vendor Mapping          16495 non-null  object
 8   GL Mapping              0 non-null      float64
 9   Final Category          16495 non-null  object
 10  Final Mapping           16495 non-null  object
 11  Company                 0 non-null      float64
 12  Additional Notes        0 non-null      float64
 13  Unique Id               16495 non-null  object
 14  Voucher                 16495 non-null  int64
 15  Invc Date               16495 non-null  datetime64[ns]
 16  Vendor Invoice          16495 non-null  object
 17  Description             16495 non-null  object
 18  GL-Acct                 16495 non-null  object
 19  GL Account Description  16495 non-null  object
 20  Vendor                  16495 non-null  object
 21  Vendor Code             16495 non-null  object
 22  Invoice Line Amt        16495 non-null  float64
 23  PO Number               5683 non-null   object
 24  PO Line                 5683 non-null   float64
 25  Exclusion               0 non-null      float64
 26  Notes                   828 non-null    object
dtypes: datetime64[ns](2), float64(8), int64(1), object(16)
memory usage: 3.4+ MB

In [60]:
df = df.drop(df.columns[0], axis=1)
df = df.dropna(axis=1)

In [61]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16495 entries, 0 to 16494
Data columns (total 19 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Original Vendor         16495 non-null  object
 1   Deduped Vendor          16495 non-null  object
 2   Invoice Description     16495 non-null  object
 3   GL Description          16495 non-null  object
 4   Amount                  16495 non-null  float64
 5   Date                    16495 non-null  datetime64[ns]
 6   Vendor Mapping          16495 non-null  object
 7   Final Category          16495 non-null  object
 8   Final Mapping           16495 non-null  object
 9   Unique Id               16495 non-null  object
 10  Voucher                 16495 non-null  int64
 11  Invc Date               16495 non-null  datetime64[ns]
 12  Vendor Invoice          16495 non-null  object
 13  Description             16495 non-null  object
 14  GL-Acct                 16495 non-null  object
 15  GL Account Description  16495 non-null  object
 16  Vendor                  16495 non-null  object
 17  Vendor Code             16495 non-null  object
 18  Invoice Line Amt        16495 non-null  float64
dtypes: datetime64[ns](2), float64(2), int64(1), object(14)
memory usage: 2.4+ MB

In [62]:
final_cat = ["Vendor Mapping", "Final Category", "Final Mapping"]

unique_finals = {}
for f in final_cat:
    unique_finals[f] = df[f].unique()
unique_finals

{'Vendor Mapping': array(['IT Software', 'Crates & Pallets', 'Unmapped', 'Relocation Svcs',
        'Facility / Property Rent', 'Non IT Temp Labor',
        'Security Personnel', 'Emergency Kits', 'LTL/FTL',
        'Barcode Readers', 'Packaging & Shipping Supplies', 'DAIRY',
        'Disinfection Services', 'Collection Services', 'OATS',
        'IT Consulting & Systems Integrators', 'POTATO',
        'Flexible Packaging', 'Employee Benefits', 'OILS', 'EGG',
        'Forklifts', 'VEGETABLES', 'BAKERY', 'Janitorial Supplies',
        'Intra-company transfer', 'General Industrial Supplies',
        'XANTHAN GUM', 'Corrugated', 'Food Packing Equipment',
        'VARIOUS FOODS', 'Advisory & Management Consulting', 'PASTA',
        'COCOA', 'RICE', 'BANANA', 'LEGUMES',
        'Landscape/Snow removal Svcs', 'Legal Services',
        'Advertising (Creative) Services', 'Uniforms', 'APPLE',
        'SPIRULINA', 'Pest Control',
        'Facility - Access control/ Surveillance/ Security',
        'General Contractors', 'FLAVORS', 'INGREDIENTS', 'Copiers/MFPs',
        'Food Inspection Equipment', 'SUGAR', 'SPICES',
        'Executive Search / Recruiting', 'Corporate Insurance',
        'PROBIOTICS', 'Fleet', 'LOADING DOCK EQUIPMENT ', 'SWEET CORN',
        'ENZYMES', 'SEEDS', 'Safety Supplies', 'WHEAT', 'TOMATO',
        'Electrical Supplies', 'SPINACH', 'P-Card',
        'Accounting & Auditing', 'BROCCOLI', 'STARCH', 'Cloud Services',
        'SOY PROTEINS', 'PEANUT BUTTER', 'Water filters',
        'Payroll Services', 'Bank/Other Finance Charges',
        'Food Production Equipment', 'GRASS JUICE', 'CITRUS', 'MUSHROOMS',
        'Waste Management', 'CHICKEN', 'MAPLE', 'Office Furniture',
        'STRAWBERRIES', 'RASPBERRY', 'Marketing Software', 'BLACKBERRY',
        'HR Consulting', 'Taxes', 'Online Advertising',
        'Utilities - Electric', 'Utilities - Water'], dtype=object),
 'Final Category': array(['Technology', 'Packing & Shipping Supplies', 'Unaddressable',
        'Transportation & Logistics', 'Real Estate & Facilities', 'HR',
        'COGS - FOODS', 'Administrative', 'COGS - OILS', 'MRO',
        'COGS - EQUIPMENT', 'Professional Services', 'Marketing',
        'Finance & Risk', 'Fleet', 'Utilities'], dtype=object),
 'Final Mapping': array(['IT Software', 'Crates & Pallets', 'Unmapped', 'Relocation Svcs',
        'Facility / Property Rent', 'Non IT Temp Labor',
        'Security Personnel', 'Emergency Kits', 'LTL/FTL',
        'Barcode Readers', 'Packaging & Shipping Supplies', 'DAIRY',
        'Disinfection Services', 'Collection Services', 'OATS',
        'IT Consulting & Systems Integrators', 'POTATO',
        'Flexible Packaging', 'Employee Benefits', 'OILS', 'EGG',
        'Forklifts', 'VEGETABLES', 'BAKERY', 'Janitorial Supplies',
        'Intra-company transfer', 'General Industrial Supplies',
        'XANTHAN GUM', 'Corrugated', 'Food Packing Equipment',
        'VARIOUS FOODS', 'Advisory & Management Consulting', 'PASTA',
        'COCOA', 'RICE', 'BANANA', 'LEGUMES',
        'Landscape/Snow removal Svcs', 'Legal Services',
        'Advertising (Creative) Services', 'Uniforms', 'APPLE',
        'SPIRULINA', 'Pest Control',
        'Facility - Access control/ Surveillance/ Security',
        'General Contractors', 'FLAVORS', 'INGREDIENTS', 'Copiers/MFPs',
        'Food Inspection Equipment', 'SUGAR', 'SPICES',
        'Executive Search / Recruiting', 'Corporate Insurance',
        'PROBIOTICS', 'Fleet', 'LOADING DOCK EQUIPMENT ', 'SWEET CORN',
        'ENZYMES', 'SEEDS', 'Safety Supplies', 'WHEAT', 'TOMATO',
        'Electrical Supplies', 'SPINACH', 'P-Card',
        'Accounting & Auditing', 'BROCCOLI', 'STARCH', 'Cloud Services',
        'SOY PROTEINS', 'PEANUT BUTTER', 'Water filters',
        'Payroll Services', 'Bank/Other Finance Charges',
        'Food Production Equipment', 'GRASS JUICE', 'CITRUS', 'MUSHROOMS',
        'Waste Management', 'CHICKEN', 'MAPLE', 'Office Furniture',
        'STRAWBERRIES', 'RASPBERRY', 'Marketing Software', 'BLACKBERRY',
        'HR Consulting', 'Taxes', 'Online Advertising',
        'Utilities - Electric', 'Utilities - Water'], dtype=object)}

In [63]:
df.iloc[10]

Original Vendor                                  Premier Employee Solutions
Deduped Vendor                                   Premier Employee Solutions
Invoice Description                                      Payroll - Shipping
GL Description                                           Payroll - Shipping
Amount                                                                884.3
Date                                                    2022-05-01 00:00:00
Vendor Mapping                                            Non IT Temp Labor
Final Category                                                           HR
Final Mapping                                             Non IT Temp Labor
Unique Id                 Premier Employee Solutions-1092859-IN-98205--8...
Voucher                                                               98205
Invc Date                                               2022-05-01 00:00:00
Vendor Invoice                                                   1092859-IN
Description                                              Payroll - Shipping
GL-Acct                                                             5610-70
GL Account Description                                   Payroll - Shipping
Vendor                                           Premier Employee Solutions
Vendor Code                                                        premempl
Invoice Line Amt                                                      884.3
Name: 10, dtype: object

In [64]:
split_column_index = df.columns.get_loc('Unique Id')

df1 = df.iloc[:, :split_column_index]
df2 = df.iloc[:, split_column_index:]

In [86]:
index = random.randint(0, df1.shape[0])
print("ORIGINAL DATA:")
print(df2.iloc[index])
print("\n")
print("CREATED DATA:")
print(df1.iloc[index])

ORIGINAL DATA:
Unique Id                 Batory Foods-INV-1305536-IN-99924-PO-000003026...
Voucher                                                               99924
Invc Date                                               2022-06-30 00:00:00
Vendor Invoice                                               INV-1305536-IN
Description                                               Sugar White Stock
GL-Acct                                                             1200-00
GL Account Description                                Inventory - Raw Goods
Vendor                                                         Batory Foods
Vendor Code                                                        BatoFood
Invoice Line Amt                                                    19656.0
Name: 3221, dtype: object


CREATED DATA:
Original Vendor                 Batory Foods
Deduped Vendor                  Batory Foods
Invoice Description        Sugar White Stock
GL Description         Inventory - Raw Goods
Amount                               19656.0
Date                     2022-06-30 00:00:00
Vendor Mapping                         COCOA
Final Category                  COGS - FOODS
Final Mapping                          COCOA
Name: 3221, dtype: object

In [94]:
similar = [ ["Final Mapping", "Vendor Mapping"], 
            ["Original Vendor", "Vendor"], 
            ["Deduped Vendor", "Original Vendor"],
            ["Date", "Invc Date"],
            ["Invoice Description", "Description"],
            ["Amount", "Invoice Line Amt"],
            ["GL Account Description", "GL Description"] ]

In [100]:
difference_map = {}
for s in similar:
    difference_map[s[0] + " vs " + s[1]] = (df[s[0]] != df[s[1]])

In [102]:
difference_map_counts = {}
for k, v in difference_map.items():
    difference_map_counts[k] = v.value_counts()

In [105]:
difference_map_counts

{'Final Mapping vs Vendor Mapping': False    16495
 dtype: int64,
 'Original Vendor vs Vendor': False    16495
 dtype: int64,
 'Deduped Vendor vs Original Vendor': False    16487
 True         8
 dtype: int64,
 'Date vs Invc Date': False    16495
 dtype: int64,
 'Invoice Description vs Description': False    16495
 dtype: int64,
 'Amount vs Invoice Line Amt': False    16495
 dtype: int64,
 'GL Account Description vs GL Description': False    16495
 dtype: int64}

In [106]:
df[difference_map["Deduped Vendor vs Original Vendor"] == True]

,Original Vendor,Deduped Vendor,Invoice Description,GL Description,Amount,Date,Vendor Mapping,Final Category,Final Mapping,Unique Id,Voucher,Invc Date,Vendor Invoice,Description,GL-Acct,GL Account Description,Vendor,Vendor Code,Invoice Line Amt
3231,Cibc Bank Usa,Cibc Visa,Bank Charges,Bank Charges,546.00,2022-06-30,Bank/Other Finance Charges,Finance & Risk,Bank/Other Finance Charges,Cibc Bank Usa-063022-IN-99870--546-44742-Bank ...,99870,2022-06-30,063022-IN,Bank Charges,6020-90,Bank Charges,Cibc Bank Usa,CIBC,546.00
4599,Cibc Bank Usa,Cibc Visa,Bank Charges,Bank Charges,380.04,2022-07-29,Bank/Other Finance Charges,Finance & Risk,Bank/Other Finance Charges,Cibc Bank Usa-071922-IN-101029--380.04-44771-B...,101029,2022-07-29,071922-IN,Bank Charges,6020-90,Bank Charges,Cibc Bank Usa,CIBC,380.04
5291,Cibc Bank Usa,Cibc Visa,Bank Charges,Bank Charges,30.00,2022-08-01,Bank/Other Finance Charges,Finance & Risk,Bank/Other Finance Charges,Cibc Bank Usa-090122-IN-101946--30-44774-Bank ...,101946,2022-08-01,090122-IN,Bank Charges,6020-90,Bank Charges,Cibc Bank Usa,CIBC,30.00
5481,Cibc Bank Usa,Cibc Visa,Bank Charges,Bank Charges,40.00,2022-08-03,Bank/Other Finance Charges,Finance & Risk,Bank/Other Finance Charges,Cibc Bank Usa-080322-IN-101949--40-44776-Bank ...,101949,2022-08-03,080322-IN,Bank Charges,6020-90,Bank Charges,Cibc Bank Usa,CIBC,40.00
5523,Cibc Bank Usa,Cibc Visa,Bank Charges,Bank Charges,15.00,2022-08-04,Bank/Other Finance Charges,Finance & Risk,Bank/Other Finance Charges,Cibc Bank Usa-080422-IN-101944--15-44777-Bank ...,101944,2022-08-04,080422-IN,Bank Charges,6020-90,Bank Charges,Cibc Bank Usa,CIBC,15.00
12602,Cibc Bank Usa,Cibc Visa,Bank Charges,Bank Charges,15.00,2022-12-21,Bank/Other Finance Charges,Finance & Risk,Bank/Other Finance Charges,Cibc Bank Usa-121522-IN-106401--15-44916-Bank ...,106401,2022-12-21,121522-IN,Bank Charges,6020-90,Bank Charges,Cibc Bank Usa,CIBC,15.00
15091,Cibc Bank Usa,Cibc Visa,Bank Charges,Bank Charges,121.57,2023-03-31,Bank/Other Finance Charges,Finance & Risk,Bank/Other Finance Charges,Cibc Bank Usa-032123-IN-108992--121.57-45016-B...,108992,2023-03-31,032123-IN,Bank Charges,6020-90,Bank Charges,Cibc Bank Usa,CIBC,121.57
15968,Cibc Bank Usa,Cibc Visa,Bank Charges,Bank Charges,268.14,2023-04-30,Bank/Other Finance Charges,Finance & Risk,Bank/Other Finance Charges,Cibc Bank Usa-041823-IN-109733--268.14-45046-B...,109733,2023-04-30,041823-IN,Bank Charges,6020-90,Bank Charges,Cibc Bank Usa,CIBC,268.14